version: '3.8'
services:
  tomcat:
    build: .
    ports:
      - "8080:8080"
    #depends_on:
      #- mysql
  #mysql:
    #container_name: mysql
    #image: mysql
    #ports:
      #- "3307:3306"
    #environment:
      #MYSQL_ROOT_PASSWORD: admin1234
      #MYSQL_DATABASE: sistema
      #MYSQL_USER: prueba
      #MYSQL_PASSWORD: test1234
    #volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql